//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 06:01:58 PM CST 
//


package com.orangeleap.tangerine.ws.schema.v3_2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.orangeleap.tangerine.ws.schema.v3_2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Touchpoint_QNAME = new QName("http://www.orangeleap.com/orangeleap/typesv3_2", "Touchpoint");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.orangeleap.tangerine.ws.schema.v3_2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap }
     * 
     */
    public com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap createAbstractCustomizableEntityCustomFieldMap() {
        return new com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap();
    }

    /**
     * Create an instance of {@link FindConstituentsRequest }
     * 
     */
    public FindConstituentsRequest createFindConstituentsRequest() {
        return new FindConstituentsRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Filter }
     * 
     */
    public Filter createFilter() {
        return new Filter();
    }

    /**
     * Create an instance of {@link DateFilter }
     * 
     */
    public DateFilter createDateFilter() {
        return new DateFilter();
    }

    /**
     * Create an instance of {@link SaveOrUpdatePledgeRequest }
     * 
     */
    public SaveOrUpdatePledgeRequest createSaveOrUpdatePledgeRequest() {
        return new SaveOrUpdatePledgeRequest();
    }

    /**
     * Create an instance of {@link Pledge }
     * 
     */
    public Pledge createPledge() {
        return new Pledge();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeRequest }
     * 
     */
    public GetConstituentPledgeRequest createGetConstituentPledgeRequest() {
        return new GetConstituentPledgeRequest();
    }

    /**
     * Create an instance of {@link GetCustomTableConstituentContextFieldRequest }
     * 
     */
    public GetCustomTableConstituentContextFieldRequest createGetCustomTableConstituentContextFieldRequest() {
        return new GetCustomTableConstituentContextFieldRequest();
    }

    /**
     * Create an instance of {@link CustomTable }
     * 
     */
    public CustomTable createCustomTable() {
        return new CustomTable();
    }

    /**
     * Create an instance of {@link GetDetailCustomTableRowsResponse }
     * 
     */
    public GetDetailCustomTableRowsResponse createGetDetailCustomTableRowsResponse() {
        return new GetDetailCustomTableRowsResponse();
    }

    /**
     * Create an instance of {@link CustomTableRow }
     * 
     */
    public CustomTableRow createCustomTableRow() {
        return new CustomTableRow();
    }

    /**
     * Create an instance of {@link GetJobStatusRequest }
     * 
     */
    public GetJobStatusRequest createGetJobStatusRequest() {
        return new GetJobStatusRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByListIdResponse }
     * 
     */
    public GetConstituentByListIdResponse createGetConstituentByListIdResponse() {
        return new GetConstituentByListIdResponse();
    }

    /**
     * Create an instance of {@link Constituent }
     * 
     */
    public Constituent createConstituent() {
        return new Constituent();
    }

    /**
     * Create an instance of {@link AddPickListItemByNameRequest }
     * 
     */
    public AddPickListItemByNameRequest createAddPickListItemByNameRequest() {
        return new AddPickListItemByNameRequest();
    }

    /**
     * Create an instance of {@link GetListEntityRelatedCustomTablesRequest }
     * 
     */
    public GetListEntityRelatedCustomTablesRequest createGetListEntityRelatedCustomTablesRequest() {
        return new GetListEntityRelatedCustomTablesRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdatePledgeResponse }
     * 
     */
    public SaveOrUpdatePledgeResponse createSaveOrUpdatePledgeResponse() {
        return new SaveOrUpdatePledgeResponse();
    }

    /**
     * Create an instance of {@link ImportResponse }
     * 
     */
    public ImportResponse createImportResponse() {
        return new ImportResponse();
    }

    /**
     * Create an instance of {@link GetConstituentByIdResponse }
     * 
     */
    public GetConstituentByIdResponse createGetConstituentByIdResponse() {
        return new GetConstituentByIdResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdateRecurringGiftRequest }
     * 
     */
    public SaveOrUpdateRecurringGiftRequest createSaveOrUpdateRecurringGiftRequest() {
        return new SaveOrUpdateRecurringGiftRequest();
    }

    /**
     * Create an instance of {@link RecurringGift }
     * 
     */
    public RecurringGift createRecurringGift() {
        return new RecurringGift();
    }

    /**
     * Create an instance of {@link ListEntitiesRequest }
     * 
     */
    public ListEntitiesRequest createListEntitiesRequest() {
        return new ListEntitiesRequest();
    }

    /**
     * Create an instance of {@link StringMap }
     * 
     */
    public StringMap createStringMap() {
        return new StringMap();
    }

    /**
     * Create an instance of {@link GetSegmentationByIdResponse }
     * 
     */
    public GetSegmentationByIdResponse createGetSegmentationByIdResponse() {
        return new GetSegmentationByIdResponse();
    }

    /**
     * Create an instance of {@link GetConstituentGiftCountRequest }
     * 
     */
    public GetConstituentGiftCountRequest createGetConstituentGiftCountRequest() {
        return new GetConstituentGiftCountRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeCountRequest }
     * 
     */
    public GetSegmentationListByTypeCountRequest createGetSegmentationListByTypeCountRequest() {
        return new GetSegmentationListByTypeCountRequest();
    }

    /**
     * Create an instance of {@link ReadCustomTableByNameResponse }
     * 
     */
    public ReadCustomTableByNameResponse createReadCustomTableByNameResponse() {
        return new ReadCustomTableByNameResponse();
    }

    /**
     * Create an instance of {@link GetCustomTableRowCountResponse }
     * 
     */
    public GetCustomTableRowCountResponse createGetCustomTableRowCountResponse() {
        return new GetCustomTableRowCountResponse();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeCountResponse }
     * 
     */
    public GetConstituentPledgeCountResponse createGetConstituentPledgeCountResponse() {
        return new GetConstituentPledgeCountResponse();
    }

    /**
     * Create an instance of {@link ListCustomTableFieldsResponse }
     * 
     */
    public ListCustomTableFieldsResponse createListCustomTableFieldsResponse() {
        return new ListCustomTableFieldsResponse();
    }

    /**
     * Create an instance of {@link CustomTableField }
     * 
     */
    public CustomTableField createCustomTableField() {
        return new CustomTableField();
    }

    /**
     * Create an instance of {@link GetCustomTableConstituentContextFieldResponse }
     * 
     */
    public GetCustomTableConstituentContextFieldResponse createGetCustomTableConstituentContextFieldResponse() {
        return new GetCustomTableConstituentContextFieldResponse();
    }

    /**
     * Create an instance of {@link GetJobResultResponse }
     * 
     */
    public GetJobResultResponse createGetJobResultResponse() {
        return new GetJobResultResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeRequest }
     * 
     */
    public GetSegmentationListByTypeRequest createGetSegmentationListByTypeRequest() {
        return new GetSegmentationListByTypeRequest();
    }

    /**
     * Create an instance of {@link FindConstituentsResponse }
     * 
     */
    public FindConstituentsResponse createFindConstituentsResponse() {
        return new FindConstituentsResponse();
    }

    /**
     * Create an instance of {@link ReadCustomTableFieldByIdResponse }
     * 
     */
    public ReadCustomTableFieldByIdResponse createReadCustomTableFieldByIdResponse() {
        return new ReadCustomTableFieldByIdResponse();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeResponse }
     * 
     */
    public GetConstituentPledgeResponse createGetConstituentPledgeResponse() {
        return new GetConstituentPledgeResponse();
    }

    /**
     * Create an instance of {@link GetConstituentGiftSummaryResponse }
     * 
     */
    public GetConstituentGiftSummaryResponse createGetConstituentGiftSummaryResponse() {
        return new GetConstituentGiftSummaryResponse();
    }

    /**
     * Create an instance of {@link GiftSummary }
     * 
     */
    public GiftSummary createGiftSummary() {
        return new GiftSummary();
    }

    /**
     * Create an instance of {@link BulkAddCommunicationHistoryResponse }
     * 
     */
    public BulkAddCommunicationHistoryResponse createBulkAddCommunicationHistoryResponse() {
        return new BulkAddCommunicationHistoryResponse();
    }

    /**
     * Create an instance of {@link ReadCustomTableByIdResponse }
     * 
     */
    public ReadCustomTableByIdResponse createReadCustomTableByIdResponse() {
        return new ReadCustomTableByIdResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListCountResponse }
     * 
     */
    public GetSegmentationListCountResponse createGetSegmentationListCountResponse() {
        return new GetSegmentationListCountResponse();
    }

    /**
     * Create an instance of {@link GetPickListByNameRequest }
     * 
     */
    public GetPickListByNameRequest createGetPickListByNameRequest() {
        return new GetPickListByNameRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateGiftRequest }
     * 
     */
    public SaveOrUpdateGiftRequest createSaveOrUpdateGiftRequest() {
        return new SaveOrUpdateGiftRequest();
    }

    /**
     * Create an instance of {@link Gift }
     * 
     */
    public Gift createGift() {
        return new Gift();
    }

    /**
     * Create an instance of {@link SaveOrUpdateRecurringGiftResponse }
     * 
     */
    public SaveOrUpdateRecurringGiftResponse createSaveOrUpdateRecurringGiftResponse() {
        return new SaveOrUpdateRecurringGiftResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListCountRequest }
     * 
     */
    public GetSegmentationListCountRequest createGetSegmentationListCountRequest() {
        return new GetSegmentationListCountRequest();
    }

    /**
     * Create an instance of {@link GetCustomTableTitleFieldResponse }
     * 
     */
    public GetCustomTableTitleFieldResponse createGetCustomTableTitleFieldResponse() {
        return new GetCustomTableTitleFieldResponse();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryRequest }
     * 
     */
    public GetCommunicationHistoryRequest createGetCommunicationHistoryRequest() {
        return new GetCommunicationHistoryRequest();
    }

    /**
     * Create an instance of {@link GetPickListsRequest }
     * 
     */
    public GetPickListsRequest createGetPickListsRequest() {
        return new GetPickListsRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateCommunicationHistoryRequest }
     * 
     */
    public SaveOrUpdateCommunicationHistoryRequest createSaveOrUpdateCommunicationHistoryRequest() {
        return new SaveOrUpdateCommunicationHistoryRequest();
    }

    /**
     * Create an instance of {@link CommunicationHistory }
     * 
     */
    public CommunicationHistory createCommunicationHistory() {
        return new CommunicationHistory();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryCountResponse }
     * 
     */
    public GetCommunicationHistoryCountResponse createGetCommunicationHistoryCountResponse() {
        return new GetCommunicationHistoryCountResponse();
    }

    /**
     * Create an instance of {@link GetCustomTableRowsResponse }
     * 
     */
    public GetCustomTableRowsResponse createGetCustomTableRowsResponse() {
        return new GetCustomTableRowsResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeCountResponse }
     * 
     */
    public GetSegmentationListByTypeCountResponse createGetSegmentationListByTypeCountResponse() {
        return new GetSegmentationListByTypeCountResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListResponse }
     * 
     */
    public GetSegmentationListResponse createGetSegmentationListResponse() {
        return new GetSegmentationListResponse();
    }

    /**
     * Create an instance of {@link Segmentation }
     * 
     */
    public Segmentation createSegmentation() {
        return new Segmentation();
    }

    /**
     * Create an instance of {@link ReadCustomTableByIdRequest }
     * 
     */
    public ReadCustomTableByIdRequest createReadCustomTableByIdRequest() {
        return new ReadCustomTableByIdRequest();
    }

    /**
     * Create an instance of {@link GetSegmentationByNameRequest }
     * 
     */
    public GetSegmentationByNameRequest createGetSegmentationByNameRequest() {
        return new GetSegmentationByNameRequest();
    }

    /**
     * Create an instance of {@link GetCustomTableRowCountRequest }
     * 
     */
    public GetCustomTableRowCountRequest createGetCustomTableRowCountRequest() {
        return new GetCustomTableRowCountRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateGiftResponse }
     * 
     */
    public SaveOrUpdateGiftResponse createSaveOrUpdateGiftResponse() {
        return new SaveOrUpdateGiftResponse();
    }

    /**
     * Create an instance of {@link ReadCustomTableFieldByIdRequest }
     * 
     */
    public ReadCustomTableFieldByIdRequest createReadCustomTableFieldByIdRequest() {
        return new ReadCustomTableFieldByIdRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByIdRequest }
     * 
     */
    public GetConstituentByIdRequest createGetConstituentByIdRequest() {
        return new GetConstituentByIdRequest();
    }

    /**
     * Create an instance of {@link GetConstituentGiftSummaryRequest }
     * 
     */
    public GetConstituentGiftSummaryRequest createGetConstituentGiftSummaryRequest() {
        return new GetConstituentGiftSummaryRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByPaymentSourceResponse }
     * 
     */
    public GetConstituentByPaymentSourceResponse createGetConstituentByPaymentSourceResponse() {
        return new GetConstituentByPaymentSourceResponse();
    }

    /**
     * Create an instance of {@link SaveOrUpdateCustomTableRowRequest }
     * 
     */
    public SaveOrUpdateCustomTableRowRequest createSaveOrUpdateCustomTableRowRequest() {
        return new SaveOrUpdateCustomTableRowRequest();
    }

    /**
     * Create an instance of {@link GetEntityRequest }
     * 
     */
    public GetEntityRequest createGetEntityRequest() {
        return new GetEntityRequest();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryCountRequest }
     * 
     */
    public GetCommunicationHistoryCountRequest createGetCommunicationHistoryCountRequest() {
        return new GetCommunicationHistoryCountRequest();
    }

    /**
     * Create an instance of {@link ImportDataRequest }
     * 
     */
    public ImportDataRequest createImportDataRequest() {
        return new ImportDataRequest();
    }

    /**
     * Create an instance of {@link GetPickListsResponse }
     * 
     */
    public GetPickListsResponse createGetPickListsResponse() {
        return new GetPickListsResponse();
    }

    /**
     * Create an instance of {@link Picklist }
     * 
     */
    public Picklist createPicklist() {
        return new Picklist();
    }

    /**
     * Create an instance of {@link GetListMasterCustomTablesResponse }
     * 
     */
    public GetListMasterCustomTablesResponse createGetListMasterCustomTablesResponse() {
        return new GetListMasterCustomTablesResponse();
    }

    /**
     * Create an instance of {@link GetJobStatusResponse }
     * 
     */
    public GetJobStatusResponse createGetJobStatusResponse() {
        return new GetJobStatusResponse();
    }

    /**
     * Create an instance of {@link GetConstituentGiftResponse }
     * 
     */
    public GetConstituentGiftResponse createGetConstituentGiftResponse() {
        return new GetConstituentGiftResponse();
    }

    /**
     * Create an instance of {@link GetPickListByNameResponse }
     * 
     */
    public GetPickListByNameResponse createGetPickListByNameResponse() {
        return new GetPickListByNameResponse();
    }

    /**
     * Create an instance of {@link GetCustomTableTitleFieldRequest }
     * 
     */
    public GetCustomTableTitleFieldRequest createGetCustomTableTitleFieldRequest() {
        return new GetCustomTableTitleFieldRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByListIdRequest }
     * 
     */
    public GetConstituentByListIdRequest createGetConstituentByListIdRequest() {
        return new GetConstituentByListIdRequest();
    }

    /**
     * Create an instance of {@link GetJobResultRequest }
     * 
     */
    public GetJobResultRequest createGetJobResultRequest() {
        return new GetJobResultRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateConstituentRequest }
     * 
     */
    public SaveOrUpdateConstituentRequest createSaveOrUpdateConstituentRequest() {
        return new SaveOrUpdateConstituentRequest();
    }

    /**
     * Create an instance of {@link GetCustomTableRowsRequest }
     * 
     */
    public GetCustomTableRowsRequest createGetCustomTableRowsRequest() {
        return new GetCustomTableRowsRequest();
    }

    /**
     * Create an instance of {@link SearchConstituentsRequest }
     * 
     */
    public SearchConstituentsRequest createSearchConstituentsRequest() {
        return new SearchConstituentsRequest();
    }

    /**
     * Create an instance of {@link GetDetailCustomTableRowsRequest }
     * 
     */
    public GetDetailCustomTableRowsRequest createGetDetailCustomTableRowsRequest() {
        return new GetDetailCustomTableRowsRequest();
    }

    /**
     * Create an instance of {@link GetConstituentByPaymentSourceRequest }
     * 
     */
    public GetConstituentByPaymentSourceRequest createGetConstituentByPaymentSourceRequest() {
        return new GetConstituentByPaymentSourceRequest();
    }

    /**
     * Create an instance of {@link PaymentSource }
     * 
     */
    public PaymentSource createPaymentSource() {
        return new PaymentSource();
    }

    /**
     * Create an instance of {@link ReadCustomTableByNameRequest }
     * 
     */
    public ReadCustomTableByNameRequest createReadCustomTableByNameRequest() {
        return new ReadCustomTableByNameRequest();
    }

    /**
     * Create an instance of {@link GetConstituentRecurringGiftResponse }
     * 
     */
    public GetConstituentRecurringGiftResponse createGetConstituentRecurringGiftResponse() {
        return new GetConstituentRecurringGiftResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListByTypeResponse }
     * 
     */
    public GetSegmentationListByTypeResponse createGetSegmentationListByTypeResponse() {
        return new GetSegmentationListByTypeResponse();
    }

    /**
     * Create an instance of {@link SearchConstituentsResponse }
     * 
     */
    public SearchConstituentsResponse createSearchConstituentsResponse() {
        return new SearchConstituentsResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationListRequest }
     * 
     */
    public GetSegmentationListRequest createGetSegmentationListRequest() {
        return new GetSegmentationListRequest();
    }

    /**
     * Create an instance of {@link GetPaymentSourcesByConstituentIdResponse }
     * 
     */
    public GetPaymentSourcesByConstituentIdResponse createGetPaymentSourcesByConstituentIdResponse() {
        return new GetPaymentSourcesByConstituentIdResponse();
    }

    /**
     * Create an instance of {@link AddPickListItemByNameResponse }
     * 
     */
    public AddPickListItemByNameResponse createAddPickListItemByNameResponse() {
        return new AddPickListItemByNameResponse();
    }

    /**
     * Create an instance of {@link ReadCustomTableRowResponse }
     * 
     */
    public ReadCustomTableRowResponse createReadCustomTableRowResponse() {
        return new ReadCustomTableRowResponse();
    }

    /**
     * Create an instance of {@link GetPostalCodesByRadiusResponse }
     * 
     */
    public GetPostalCodesByRadiusResponse createGetPostalCodesByRadiusResponse() {
        return new GetPostalCodesByRadiusResponse();
    }

    /**
     * Create an instance of {@link PostalCodeByRadius }
     * 
     */
    public PostalCodeByRadius createPostalCodeByRadius() {
        return new PostalCodeByRadius();
    }

    /**
     * Create an instance of {@link SaveOrUpdateCustomTableRowResponse }
     * 
     */
    public SaveOrUpdateCustomTableRowResponse createSaveOrUpdateCustomTableRowResponse() {
        return new SaveOrUpdateCustomTableRowResponse();
    }

    /**
     * Create an instance of {@link GetPostalCodesByRadiusRequest }
     * 
     */
    public GetPostalCodesByRadiusRequest createGetPostalCodesByRadiusRequest() {
        return new GetPostalCodesByRadiusRequest();
    }

    /**
     * Create an instance of {@link SetEntityRequest }
     * 
     */
    public SetEntityRequest createSetEntityRequest() {
        return new SetEntityRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateCommunicationHistoryResponse }
     * 
     */
    public SaveOrUpdateCommunicationHistoryResponse createSaveOrUpdateCommunicationHistoryResponse() {
        return new SaveOrUpdateCommunicationHistoryResponse();
    }

    /**
     * Create an instance of {@link BulkAddCommunicationHistoryRequest }
     * 
     */
    public BulkAddCommunicationHistoryRequest createBulkAddCommunicationHistoryRequest() {
        return new BulkAddCommunicationHistoryRequest();
    }

    /**
     * Create an instance of {@link BulkAddCommunicationHistory }
     * 
     */
    public BulkAddCommunicationHistory createBulkAddCommunicationHistory() {
        return new BulkAddCommunicationHistory();
    }

    /**
     * Create an instance of {@link ListCustomTablesRequest }
     * 
     */
    public ListCustomTablesRequest createListCustomTablesRequest() {
        return new ListCustomTablesRequest();
    }

    /**
     * Create an instance of {@link ReadCustomTableRowRequest }
     * 
     */
    public ReadCustomTableRowRequest createReadCustomTableRowRequest() {
        return new ReadCustomTableRowRequest();
    }

    /**
     * Create an instance of {@link SetEntityResponse }
     * 
     */
    public SetEntityResponse createSetEntityResponse() {
        return new SetEntityResponse();
    }

    /**
     * Create an instance of {@link GetEntityResponse }
     * 
     */
    public GetEntityResponse createGetEntityResponse() {
        return new GetEntityResponse();
    }

    /**
     * Create an instance of {@link CreateDefaultConstituentRequest }
     * 
     */
    public CreateDefaultConstituentRequest createCreateDefaultConstituentRequest() {
        return new CreateDefaultConstituentRequest();
    }

    /**
     * Create an instance of {@link ListCustomTablesResponse }
     * 
     */
    public ListCustomTablesResponse createListCustomTablesResponse() {
        return new ListCustomTablesResponse();
    }

    /**
     * Create an instance of {@link GetConstituentPledgeCountRequest }
     * 
     */
    public GetConstituentPledgeCountRequest createGetConstituentPledgeCountRequest() {
        return new GetConstituentPledgeCountRequest();
    }

    /**
     * Create an instance of {@link GetCommunicationHistoryResponse }
     * 
     */
    public GetCommunicationHistoryResponse createGetCommunicationHistoryResponse() {
        return new GetCommunicationHistoryResponse();
    }

    /**
     * Create an instance of {@link GetConstituentRecurringGiftRequest }
     * 
     */
    public GetConstituentRecurringGiftRequest createGetConstituentRecurringGiftRequest() {
        return new GetConstituentRecurringGiftRequest();
    }

    /**
     * Create an instance of {@link ImportDataResponse }
     * 
     */
    public ImportDataResponse createImportDataResponse() {
        return new ImportDataResponse();
    }

    /**
     * Create an instance of {@link ListEntitiesResponse }
     * 
     */
    public ListEntitiesResponse createListEntitiesResponse() {
        return new ListEntitiesResponse();
    }

    /**
     * Create an instance of {@link StringMapList }
     * 
     */
    public StringMapList createStringMapList() {
        return new StringMapList();
    }

    /**
     * Create an instance of {@link GetListMasterCustomTablesRequest }
     * 
     */
    public GetListMasterCustomTablesRequest createGetListMasterCustomTablesRequest() {
        return new GetListMasterCustomTablesRequest();
    }

    /**
     * Create an instance of {@link GetListDetailCustomTablesResponse }
     * 
     */
    public GetListDetailCustomTablesResponse createGetListDetailCustomTablesResponse() {
        return new GetListDetailCustomTablesResponse();
    }

    /**
     * Create an instance of {@link ListCustomTableFieldsRequest }
     * 
     */
    public ListCustomTableFieldsRequest createListCustomTableFieldsRequest() {
        return new ListCustomTableFieldsRequest();
    }

    /**
     * Create an instance of {@link ImportRequest }
     * 
     */
    public ImportRequest createImportRequest() {
        return new ImportRequest();
    }

    /**
     * Create an instance of {@link GetConstituentRecurringGiftCountRequest }
     * 
     */
    public GetConstituentRecurringGiftCountRequest createGetConstituentRecurringGiftCountRequest() {
        return new GetConstituentRecurringGiftCountRequest();
    }

    /**
     * Create an instance of {@link GetConstituentRecurringGiftCountResponse }
     * 
     */
    public GetConstituentRecurringGiftCountResponse createGetConstituentRecurringGiftCountResponse() {
        return new GetConstituentRecurringGiftCountResponse();
    }

    /**
     * Create an instance of {@link GetConstituentGiftRequest }
     * 
     */
    public GetConstituentGiftRequest createGetConstituentGiftRequest() {
        return new GetConstituentGiftRequest();
    }

    /**
     * Create an instance of {@link SaveOrUpdateConstituentResponse }
     * 
     */
    public SaveOrUpdateConstituentResponse createSaveOrUpdateConstituentResponse() {
        return new SaveOrUpdateConstituentResponse();
    }

    /**
     * Create an instance of {@link GetPickListsCountResponse }
     * 
     */
    public GetPickListsCountResponse createGetPickListsCountResponse() {
        return new GetPickListsCountResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationByIdRequest }
     * 
     */
    public GetSegmentationByIdRequest createGetSegmentationByIdRequest() {
        return new GetSegmentationByIdRequest();
    }

    /**
     * Create an instance of {@link GetConstituentGiftCountResponse }
     * 
     */
    public GetConstituentGiftCountResponse createGetConstituentGiftCountResponse() {
        return new GetConstituentGiftCountResponse();
    }

    /**
     * Create an instance of {@link GetPaymentSourcesByConstituentIdRequest }
     * 
     */
    public GetPaymentSourcesByConstituentIdRequest createGetPaymentSourcesByConstituentIdRequest() {
        return new GetPaymentSourcesByConstituentIdRequest();
    }

    /**
     * Create an instance of {@link GetListEntityRelatedCustomTablesResponse }
     * 
     */
    public GetListEntityRelatedCustomTablesResponse createGetListEntityRelatedCustomTablesResponse() {
        return new GetListEntityRelatedCustomTablesResponse();
    }

    /**
     * Create an instance of {@link CreateDefaultConstituentResponse }
     * 
     */
    public CreateDefaultConstituentResponse createCreateDefaultConstituentResponse() {
        return new CreateDefaultConstituentResponse();
    }

    /**
     * Create an instance of {@link GetSegmentationByNameResponse }
     * 
     */
    public GetSegmentationByNameResponse createGetSegmentationByNameResponse() {
        return new GetSegmentationByNameResponse();
    }

    /**
     * Create an instance of {@link GetListDetailCustomTablesRequest }
     * 
     */
    public GetListDetailCustomTablesRequest createGetListDetailCustomTablesRequest() {
        return new GetListDetailCustomTablesRequest();
    }

    /**
     * Create an instance of {@link GetPickListsCountRequest }
     * 
     */
    public GetPickListsCountRequest createGetPickListsCountRequest() {
        return new GetPickListsCountRequest();
    }

    /**
     * Create an instance of {@link DistributionLine }
     * 
     */
    public DistributionLine createDistributionLine() {
        return new DistributionLine();
    }

    /**
     * Create an instance of {@link PicklistItem }
     * 
     */
    public PicklistItem createPicklistItem() {
        return new PicklistItem();
    }

    /**
     * Create an instance of {@link ValidValue }
     * 
     */
    public ValidValue createValidValue() {
        return new ValidValue();
    }

    /**
     * Create an instance of {@link StringMapEntry }
     * 
     */
    public StringMapEntry createStringMapEntry() {
        return new StringMapEntry();
    }

    /**
     * Create an instance of {@link ChildCustomTable }
     * 
     */
    public ChildCustomTable createChildCustomTable() {
        return new ChildCustomTable();
    }

    /**
     * Create an instance of {@link CustomField }
     * 
     */
    public CustomField createCustomField() {
        return new CustomField();
    }

    /**
     * Create an instance of {@link Site }
     * 
     */
    public Site createSite() {
        return new Site();
    }

    /**
     * Create an instance of {@link com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap.Entry }
     * 
     */
    public com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap.Entry createAbstractCustomizableEntityCustomFieldMapEntry() {
        return new com.orangeleap.tangerine.ws.schema.v3_2.AbstractCustomizableEntity.CustomFieldMap.Entry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommunicationHistory }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.orangeleap.com/orangeleap/typesv3_2", name = "Touchpoint")
    public JAXBElement<CommunicationHistory> createTouchpoint(CommunicationHistory value) {
        return new JAXBElement<CommunicationHistory>(_Touchpoint_QNAME, CommunicationHistory.class, null, value);
    }

}
